<?php
use Illuminate\Support\Facades\Route; use App\Http\Controllers\{AuthController,DashboardController,ProfileController,AdminController,DonationController,RequestController,DeliveryController};
Route::get('/', fn()=>redirect('/dashboard'));
Route::get('/login',[AuthController::class,'loginForm'])->name('login'); Route::post('/login',[AuthController::class,'login']); Route::get('/register',[AuthController::class,'registerForm']); Route::post('/register',[AuthController::class,'register']); Route::post('/logout',[AuthController::class,'logout']);
Route::middleware('auth')->group(function(){ Route::get('/dashboard',DashboardController::class); Route::get('/profile',[ProfileController::class,'show']); Route::post('/profile',[ProfileController::class,'update']); Route::post('/profile/document',[ProfileController::class,'uploadDocument']); Route::get('/donations/available',[DonationController::class,'available']);
 Route::middleware('role:ADMIN')->group(function(){ Route::get('/admin/users',[AdminController::class,'users']); Route::patch('/admin/users/{user}',[AdminController::class,'updateStatus']); Route::get('/admin/verifications',[AdminController::class,'verifications']); Route::post('/admin/verifications/{profile}',[AdminController::class,'review']); });
 Route::middleware('role:FOOD_DONOR')->group(function(){ Route::resource('donations',DonationController::class)->except(['show','destroy']); Route::post('/donations/{donation}/cancel',[DonationController::class,'cancel']); });
 Route::middleware('role:CHARITY')->group(function(){ Route::resource('requests',RequestController::class)->parameters(['requests'=>'foodRequest'])->except(['show','destroy']); Route::post('/requests/{foodRequest}/cancel',[RequestController::class,'cancel']); Route::get('/requests/{foodRequest}/reservations',[RequestController::class,'reservations']); Route::post('/requests/{foodRequest}/reservations',[RequestController::class,'reserve']); });
 Route::middleware('role:VOLUNTEER,ADMIN')->group(function(){ Route::get('/deliveries',[DeliveryController::class,'index']); Route::post('/reservations/{reservation}/delivery',[DeliveryController::class,'createFromReservation']); Route::get('/deliveries/{delivery}/edit',[DeliveryController::class,'edit']); Route::patch('/deliveries/{delivery}',[DeliveryController::class,'update']); }); });
