<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('users', function (Blueprint $t) { $t->id('user_id'); $t->string('full_name'); $t->string('email')->unique(); $t->string('password_hash'); $t->string('phone_no')->nullable(); $t->enum('role',['FOOD_DONOR','CHARITY','VOLUNTEER','ADMIN']); $t->enum('account_status',['ACTIVE','INACTIVE','SUSPENDED','DELETED'])->default('ACTIVE'); $t->timestamp('created_at')->useCurrent(); });
  Schema::create('partner_profiles', function (Blueprint $t) { $t->id('profile_id'); $t->foreignId('user_id')->unique()->constrained('users','user_id'); $t->text('address')->nullable(); $t->enum('verification_status',['PENDING','APPROVED','REJECTED'])->default('PENDING'); $t->timestamp('created_at')->useCurrent(); });
  Schema::create('verification_documents', function (Blueprint $t) { $t->id('document_id'); $t->foreignId('partner_id')->constrained('partner_profiles','profile_id'); $t->string('document_type'); $t->string('file_path'); $t->enum('document_status',['PENDING','APPROVED','REJECTED'])->default('PENDING'); });
  Schema::create('verification_reviews', function (Blueprint $t) { $t->id('review_id'); $t->foreignId('partner_id')->constrained('partner_profiles','profile_id'); $t->foreignId('reviewed_by')->constrained('users','user_id'); $t->enum('decision',['APPROVED','REJECTED']); $t->text('remarks')->nullable(); $t->timestamp('reviewed_at')->useCurrent(); });
  Schema::create('user_sessions', function (Blueprint $t) { $t->id('session_id'); $t->foreignId('user_id')->constrained('users','user_id'); $t->string('session_token'); $t->string('ip_address')->nullable(); $t->text('user_agent')->nullable(); $t->timestamp('login_at')->useCurrent(); $t->timestamp('logout_at')->nullable(); $t->enum('session_status',['ACTIVE','LOGGED_OUT'])->default('ACTIVE'); });
  Schema::create('food_categories', function (Blueprint $t) { $t->id('category_id'); $t->string('category_name'); $t->text('description')->nullable(); });
  Schema::create('food_donations', function (Blueprint $t) { $t->id('donation_id'); $t->foreignId('donor_id')->constrained('partner_profiles','profile_id'); $t->foreignId('category_id')->constrained('food_categories','category_id'); $t->string('food_name'); $t->text('description')->nullable(); $t->decimal('donation_quantity',10,2); $t->decimal('current_quantity',10,2); $t->string('measurement_unit'); $t->dateTime('expiry_datetime'); $t->text('pickup_address'); $t->string('storage_type')->nullable(); $t->string('halal_status')->nullable(); $t->enum('donation_status',['AVAILABLE','RESERVED','COMPLETED','CANCELLED','EXPIRED'])->default('AVAILABLE'); $t->timestamp('donation_datetime')->useCurrent(); });
  Schema::create('donation_photos', function (Blueprint $t) { $t->id('photo_id'); $t->foreignId('donation_id')->constrained('food_donations','donation_id'); $t->string('file_path'); $t->timestamp('uploaded_at')->useCurrent(); });
  Schema::create('donation_status_histories', function (Blueprint $t) { $t->id('donation_history_id'); $t->foreignId('donation_id')->constrained('food_donations','donation_id'); $t->string('old_status')->nullable(); $t->string('new_status'); $t->foreignId('changed_by')->constrained('users','user_id'); $t->timestamp('changed_at')->useCurrent(); $t->text('remarks')->nullable(); });
  Schema::create('food_requests', function (Blueprint $t) { $t->id('request_id'); $t->foreignId('charity_id')->constrained('partner_profiles','profile_id'); $t->foreignId('category_id')->constrained('food_categories','category_id'); $t->decimal('requested_quantity',10,2); $t->decimal('fulfilled_quantity',10,2)->default(0); $t->string('unit'); $t->dateTime('request_deadline'); $t->enum('request_status',['OPEN','FULFILLED','CANCELLED'])->default('OPEN'); $t->timestamp('created_at')->useCurrent(); });
  Schema::create('reservations', function (Blueprint $t) { $t->id('reservation_id'); $t->foreignId('request_id')->constrained('food_requests','request_id'); $t->foreignId('donation_id')->constrained('food_donations','donation_id'); $t->decimal('reserved_quantity',10,2); $t->enum('reservation_status',['PENDING','CONFIRMED','CANCELLED','COMPLETED'])->default('CONFIRMED'); $t->dateTime('pickup_deadline'); $t->timestamp('created_at')->useCurrent(); });
  Schema::create('delivery_tasks', function (Blueprint $t) { $t->id('delivery_id'); $t->foreignId('reservation_id')->unique()->constrained('reservations','reservation_id'); $t->foreignId('volunteer_id')->constrained('partner_profiles','profile_id'); $t->text('pickup_address'); $t->text('delivery_address'); $t->enum('delivery_status',['ASSIGNED','PICKED_UP','DELIVERED','CANCELLED'])->default('ASSIGNED'); $t->timestamp('assigned_at')->useCurrent(); $t->timestamp('picked_up_at')->nullable(); $t->timestamp('delivered_at')->nullable(); });
  Schema::create('delivery_status_histories', function (Blueprint $t) { $t->id('delivery_history_id'); $t->foreignId('delivery_id')->constrained('delivery_tasks','delivery_id'); $t->string('old_status')->nullable(); $t->string('new_status'); $t->foreignId('changed_by')->constrained('users','user_id'); $t->timestamp('changed_at')->useCurrent(); $t->text('remarks')->nullable(); });
 }
 public function down(): void { foreach (array_reverse(['users','partner_profiles','verification_documents','verification_reviews','user_sessions','food_categories','food_donations','donation_photos','donation_status_histories','food_requests','reservations','delivery_tasks','delivery_status_histories']) as $table) Schema::dropIfExists($table); }
};
